In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('OnlineNewsPopularity.csv')
df.head()

url  timedelta  \
0  http://mashable.com/2013/01/07/amazon-instant-...      731.0   
1  http://mashable.com/2013/01/07/ap-samsung-spon...      731.0   
2  http://mashable.com/2013/01/07/apple-40-billio...      731.0   
3  http://mashable.com/2013/01/07/astronaut-notre...      731.0   
4   http://mashable.com/2013/01/07/att-u-verse-apps/      731.0   

   n_tokens_title  n_tokens_content  n_unique_tokens  n_non_stop_words  \
0            12.0             219.0         0.663594               1.0   
1             9.0             255.0         0.604743               1.0   
2             9.0             211.0         0.575130               1.0   
3             9.0             531.0         0.503788               1.0   
4            13.0            1072.0         0.415646               1.0   

   n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  num_imgs  ...  \
0                  0.815385        4.0             2.0       1.0  ...   
1                  0.791946        3.0             1.0       1.0  ...   
2                  0.663866        3.0             1.0       1.0  ...   
3                  0.665635        9.0             0.0       1.0  ...   
4                  0.540890       19.0            19.0      20.0  ...   

   min_positive_polarity  max_positive_polarity  avg_negative_polarity  \
0               0.100000                    0.7              -0.350000   
1               0.033333                    0.7              -0.118750   
2               0.100000                    1.0              -0.466667   
3               0.136364                    0.8              -0.369697   
4               0.033333                    1.0              -0.220192   

   min_negative_polarity  max_negative_polarity  title_subjectivity  \
0                 -0.600              -0.200000            0.500000   
1                 -0.125              -0.100000            0.000000   
2                 -0.800              -0.133333            0.000000   
3                 -0.600              -0.166667            0.000000   
4                 -0.500              -0.050000            0.454545   

   title_sentiment_polarity  abs_title_subjectivity  \
0                 -0.187500                0.000000   
1                  0.000000                0.500000   
2                  0.000000                0.500000   
3                  0.000000                0.500000   
4                  0.136364                0.045455   

   abs_title_sentiment_polarity  shares  
0                      0.187500     593  
1                      0.000000     711  
2                      0.000000    1500  
3                      0.000000    1200  
4                      0.136364     505  

[5 rows x 61 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39644 entries, 0 to 39643
Data columns (total 61 columns):
url                               39644 non-null object
timedelta                         39644 non-null float64
n_tokens_title                    39644 non-null float64
n_tokens_content                  39644 non-null float64
n_unique_tokens                   39644 non-null float64
n_non_stop_words                  39644 non-null float64
n_non_stop_unique_tokens          39644 non-null float64
num_hrefs                         39644 non-null float64
num_self_hrefs                    39644 non-null float64
num_imgs                          39644 non-null float64
num_videos                        39644 non-null float64
average_token_length              39644 non-null float64
num_keywords                      39644 non-null float64
data_channel_is_lifestyle         39644 non-null float64
 data_channel_is_entertainment    39644 non-null float64
data_channel_is_bus               396

In [4]:
df1 = df.drop('url', axis = 1)
df1.head()

timedelta  n_tokens_title  n_tokens_content  n_unique_tokens  \
0      731.0            12.0             219.0         0.663594   
1      731.0             9.0             255.0         0.604743   
2      731.0             9.0             211.0         0.575130   
3      731.0             9.0             531.0         0.503788   
4      731.0            13.0            1072.0         0.415646   

   n_non_stop_words  n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  \
0               1.0                  0.815385        4.0             2.0   
1               1.0                  0.791946        3.0             1.0   
2               1.0                  0.663866        3.0             1.0   
3               1.0                  0.665635        9.0             0.0   
4               1.0                  0.540890       19.0            19.0   

   num_imgs  num_videos  ...  min_positive_polarity  max_positive_polarity  \
0       1.0         0.0  ...               0.100000                    0.7   
1       1.0         0.0  ...               0.033333                    0.7   
2       1.0         0.0  ...               0.100000                    1.0   
3       1.0         0.0  ...               0.136364                    0.8   
4      20.0         0.0  ...               0.033333                    1.0   

   avg_negative_polarity  min_negative_polarity  max_negative_polarity  \
0              -0.350000                 -0.600              -0.200000   
1              -0.118750                 -0.125              -0.100000   
2              -0.466667                 -0.800              -0.133333   
3              -0.369697                 -0.600              -0.166667   
4              -0.220192                 -0.500              -0.050000   

   title_subjectivity  title_sentiment_polarity  abs_title_subjectivity  \
0            0.500000                 -0.187500                0.000000   
1            0.000000                  0.000000                0.500000   
2            0.000000                  0.000000                0.500000   
3            0.000000                  0.000000                0.500000   
4            0.454545                  0.136364                0.045455   

   abs_title_sentiment_polarity  shares  
0                      0.187500     593  
1                      0.000000     711  
2                      0.000000    1500  
3                      0.000000    1200  
4                      0.136364     505  

[5 rows x 60 columns]

In [5]:
X = df1.iloc[:, :-1]
y = df1.iloc[:, -1]

In [6]:
X.head()

timedelta  n_tokens_title  n_tokens_content  n_unique_tokens  \
0      731.0            12.0             219.0         0.663594   
1      731.0             9.0             255.0         0.604743   
2      731.0             9.0             211.0         0.575130   
3      731.0             9.0             531.0         0.503788   
4      731.0            13.0            1072.0         0.415646   

   n_non_stop_words  n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  \
0               1.0                  0.815385        4.0             2.0   
1               1.0                  0.791946        3.0             1.0   
2               1.0                  0.663866        3.0             1.0   
3               1.0                  0.665635        9.0             0.0   
4               1.0                  0.540890       19.0            19.0   

   num_imgs  num_videos  ...  avg_positive_polarity  min_positive_polarity  \
0       1.0         0.0  ...               0.378636               0.100000   
1       1.0         0.0  ...               0.286915               0.033333   
2       1.0         0.0  ...               0.495833               0.100000   
3       1.0         0.0  ...               0.385965               0.136364   
4      20.0         0.0  ...               0.411127               0.033333   

   max_positive_polarity  avg_negative_polarity  min_negative_polarity  \
0                    0.7              -0.350000                 -0.600   
1                    0.7              -0.118750                 -0.125   
2                    1.0              -0.466667                 -0.800   
3                    0.8              -0.369697                 -0.600   
4                    1.0              -0.220192                 -0.500   

   max_negative_polarity  title_subjectivity  title_sentiment_polarity  \
0              -0.200000            0.500000                 -0.187500   
1              -0.100000            0.000000                  0.000000   
2              -0.133333            0.000000                  0.000000   
3              -0.166667            0.000000                  0.000000   
4              -0.050000            0.454545                  0.136364   

   abs_title_subjectivity  abs_title_sentiment_polarity  
0                0.000000                      0.187500  
1                0.500000                      0.000000  
2                0.500000                      0.000000  
3                0.500000                      0.000000  
4                0.045455                      0.136364  

[5 rows x 59 columns]

In [7]:
y.head()

0     593
1     711
2    1500
3    1200
4     505
Name: shares, dtype: int64

In [8]:
X.corr()

timedelta  n_tokens_title  n_tokens_content  \
timedelta                        1.000000       -0.240320         -0.062867   
n_tokens_title                  -0.240320        1.000000          0.018160   
n_tokens_content                -0.062867        0.018160          1.000000   
n_unique_tokens                  0.002866       -0.005318         -0.004737   
n_non_stop_words                 0.000089       -0.004754          0.017512   
n_non_stop_unique_tokens         0.003805       -0.005420          0.000373   
num_hrefs                       -0.000832       -0.053496          0.423065   
num_self_hrefs                   0.064530       -0.014856          0.304682   
num_imgs                        -0.027636       -0.008858          0.342600   
num_videos                       0.000936        0.051460          0.103699   
average_token_length             0.130465       -0.071403          0.167789   
num_keywords                     0.046884       -0.006077          0.072845   
data_channel_is_lifestyle        0.054492       -0.070815          0.037548   
 data_channel_is_entertainment  -0.049109        0.132791          0.060200   
data_channel_is_bus              0.055788       -0.023902         -0.006105   
data_channel_is_socmed           0.076287       -0.090394          0.033424   
data_channel_is_tech             0.083277       -0.046716          0.025408   
data_channel_is_world           -0.170250        0.049223          0.055989   
kw_min_min                       0.591199       -0.110672         -0.054345   
kw_max_min                       0.029503       -0.005890          0.000066   
kw_avg_min                       0.133225       -0.031400         -0.003545   
kw_min_max                      -0.076590        0.012926         -0.022786   
kw_max_max                      -0.637824        0.120841          0.058860   
kw_avg_max                      -0.493093        0.115746         -0.096460   
kw_min_avg                      -0.157204       -0.002370         -0.022286   
kw_max_avg                      -0.051820        0.006918         -0.030496   
kw_avg_avg                      -0.163164        0.004296         -0.079624   
self_reference_min_shares       -0.011438       -0.004563         -0.030686   
self_reference_max_shares       -0.014501        0.000128          0.025657   
self_reference_avg_sharess      -0.015655        0.000661         -0.013809   
weekday_is_monday               -0.006129        0.004274         -0.002484   
weekday_is_tuesday              -0.005781        0.009322         -0.004027   
weekday_is_wednesday             0.009961        0.008935         -0.016891   
weekday_is_thursday              0.004042       -0.015472         -0.007395   
weekday_is_friday               -0.002853       -0.002015         -0.015949   
weekday_is_saturday             -0.004067       -0.015013          0.034538   
weekday_is_sunday                0.004226        0.006289          0.036394   
is_weekend                       0.000272       -0.005996          0.052024   
LDA_00                           0.080894       -0.070038          0.026218   
LDA_01                           0.004423        0.063568         -0.009724   
LDA_02                          -0.141713        0.038365          0.087266   
LDA_03                          -0.030838        0.042208         -0.140141   
LDA_04                           0.092906       -0.065063          0.041265   
global_subjectivity              0.133837       -0.056804          0.127879   
global_sentiment_polarity        0.158646       -0.072226          0.021937   
global_rate_positive_words       0.207604       -0.064951          0.133979   
global_rate_negative_words       0.010266        0.015530          0.125013   
rate_positive_words              0.198654       -0.066589          0.098960   
rate_negative_words             -0.071968        0.034186          0.101053   
avg_positive_polarity            0.126344       -0.049619          0.135123   
min

In [9]:
from sklearn.preprocessing import StandardScaler

X = StandardScaler().fit_transform(X)
X

array([[ 1.75788035,  0.75744723, -0.69521045, ..., -0.97543219,
        -1.81071884,  0.13891975],
       [ 1.75788035, -0.66165665, -0.61879381, ..., -0.26907618,
         0.83774863, -0.68965812],
       [ 1.75788035, -0.66165665, -0.71219192, ..., -0.26907618,
         0.83774863, -0.68965812],
       ...,
       [-1.61808342, -0.18862202, -0.2218518 , ...,  0.24463729,
        -1.56994907, -0.08705603],
       [-1.61808342, -2.08076053,  0.28759248, ..., -0.26907618,
         0.83774863, -0.68965812],
       [-1.61808342, -0.18862202, -0.82681689, ...,  0.67273184,
        -0.92789635,  0.41511238]])

In [10]:
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.08275367, 0.15260889, 0.2137099 , 0.2645837 , 0.31223687,
       0.35620675, 0.39928285, 0.43812046, 0.47416065, 0.50937563])

In [11]:
pca = PCA(n_components=20)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.08275377, 0.15260942, 0.21371092, 0.2645884 , 0.31224288,
       0.35621783, 0.3993087 , 0.43817534, 0.47424246, 0.50949525,
       0.54343076, 0.57538272, 0.60344769, 0.62682027, 0.64995765,
       0.6708826 , 0.69169581, 0.71221793, 0.73234482, 0.75221832])

In [12]:
pca = PCA(n_components=30)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.08275377, 0.15260942, 0.21371093, 0.26458843, 0.31224293,
       0.35621796, 0.39930891, 0.43817563, 0.4742429 , 0.50949607,
       0.54343181, 0.57538446, 0.60345014, 0.62684557, 0.6499849 ,
       0.67092622, 0.6917493 , 0.71228345, 0.73250347, 0.75238047,
       0.77152232, 0.78991901, 0.80763658, 0.82307065, 0.83783412,
       0.85162084, 0.86386782, 0.87534287, 0.88646774, 0.89682587])

In [13]:
pca = PCA(n_components=40)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.08275377, 0.15260942, 0.21371093, 0.26458843, 0.31224293,
       0.35621796, 0.39930891, 0.43817563, 0.4742429 , 0.50949607,
       0.54343181, 0.57538446, 0.60345014, 0.6268456 , 0.64998493,
       0.67092626, 0.69174935, 0.71228351, 0.73250356, 0.75238057,
       0.77152244, 0.78991914, 0.80763673, 0.82307089, 0.8378345 ,
       0.85162152, 0.86386951, 0.87534499, 0.88647121, 0.89683078,
       0.90656376, 0.9160258 , 0.92508557, 0.93306276, 0.94089591,
       0.94835252, 0.95522076, 0.96138695, 0.96675417, 0.97184806])

In [14]:
pca = PCA(n_components=37)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.08275377, 0.15260942, 0.21371093, 0.26458843, 0.31224293,
       0.35621796, 0.39930891, 0.43817563, 0.4742429 , 0.50949607,
       0.54343181, 0.57538446, 0.60345014, 0.6268456 , 0.64998493,
       0.67092626, 0.69174935, 0.71228351, 0.73250356, 0.75238057,
       0.77152244, 0.78991914, 0.80763673, 0.82307089, 0.8378345 ,
       0.85162152, 0.86386951, 0.87534499, 0.88647121, 0.89683078,
       0.90656376, 0.9160258 , 0.92508557, 0.93306276, 0.94089591,
       0.94835252, 0.95522074])

In [15]:
clf = pd.DataFrame(clf)
clf.head()

0         1         2         3         4         5         6   \
0 -1.357847 -1.884241 -1.973965 -0.000721  0.431171 -3.606547  1.421225   
1  0.196389 -4.305412 -1.135920  0.082724 -0.351637 -1.565918  3.365457   
2 -3.731178 -3.498195 -1.735067 -0.078505 -0.386993 -0.860637  2.504500   
3 -0.670098 -1.695272 -3.436230 -0.106087  1.187232 -2.169297  1.392603   
4 -4.169514 -3.718399 -1.441040 -0.131856  0.376861  0.343912 -2.743558   

         7         8         9   ...        27        28        29        30  \
0 -1.418664  0.461776  0.248742  ... -0.135075  0.276215 -0.314614 -0.178309   
1  0.305641  1.897227 -1.308060  ... -0.941402  0.572008  0.453136  0.169195   
2 -0.273694 -0.266832 -0.607381  ...  0.419986 -0.389926  0.474108 -0.796767   
3 -1.008090 -0.530943 -0.921161  ...  0.523711  0.213600  0.055545 -0.286756   
4 -1.432772  0.532729 -0.890975  ... -0.694348  0.756567  0.648723 -1.867403   

         31        32        33        34        35        36  
0  0.172681  0.641457  0.607354 -0.048295  0.179356 -0.810204  
1  0.222450 -0.439604  0.332811  0.871408  0.013891 -0.410588  
2  0.285033  0.440153 -0.187477 -0.570403 -0.692493 -0.680126  
3 -0.184348  0.378775  0.389859  0.163919 -0.345084 -0.839052  
4  0.769094 -0.075671 -0.719145 -0.018673  0.302245 -0.370568  

[5 rows x 37 columns]

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=100, max_depth=2)
clf1 = clf1.fit(X_train, y_train)

In [18]:
y_pred = clf1.predict(X_test)

In [19]:
clf1.feature_importances_

array([0.03960738, 0.        , 0.01025213, 0.01567555, 0.        ,
       0.01267634, 0.02185868, 0.        , 0.00354686, 0.00246764,
       0.00647335, 0.00209808, 0.        , 0.02957439, 0.        ,
       0.01087355, 0.01311908, 0.05064556, 0.01313194, 0.00726851,
       0.00529997, 0.00392648, 0.0084614 , 0.00442399, 0.03264973,
       0.09100151, 0.10099464, 0.07836982, 0.03607367, 0.07280021,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00988078, 0.01331871, 0.04230743, 0.02393219, 0.02972677,
       0.06963   , 0.01947714, 0.03269656, 0.01750799, 0.02315981,
       0.01159999, 0.01061395, 0.        , 0.00443067, 0.00265196,
       0.01388374, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00191184, 0.        , 0.        ])

In [20]:
RandomForestClassifier.score(clf1, X_test, y_test)

0.06003279102030521

In [21]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

          28       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         1
          49       0.00      0.00      0.00         2
          59       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         1
          64       0.00      0.00      0.00         1
          74       0.00      0.00      0.00         1
          77       0.00      0.00      0.00         1
          81       0.00      0.00      0.00         1
          86       0.00      0.00      0.00         1
          89       0.00      0.00      0.00         1
         116       0.00      0.00      0.00         1
         119       0.00      0.00      0.00         2
         121       0.00      0.00      0.00         1
         123       0.00      0.00      0.00         1
         130   

c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
