In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('breast-cancer-data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
d = {'diagnosis': {'M': 0, 'B': 1}}
df.replace(d, inplace=True)
df.head()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302          0        17.99         10.38          122.80     1001.0   
1    842517          0        20.57         17.77          132.90     1326.0   
2  84300903          0        19.69         21.25          130.00     1203.0   
3  84348301          0        11.42         20.38           77.58      386.1   
4  84358402          0        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [4]:
df.drop('id', axis=1, inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0        17.99         10.38          122.80     1001.0   
1          0        20.57         17.77          132.90     1326.0   
2          0        19.69         21.25          130.00     1203.0   
3          0        11.42         20.38           77.58      386.1   
4          0        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [9]:
np.std(df, axis = 0)

diagnosis                    0.483493
radius_mean                  3.520951
texture_mean                 4.297255
perimeter_mean              24.277619
area_mean                  351.604754
smoothness_mean              0.014052
compactness_mean             0.052766
concavity_mean               0.079650
concave points_mean          0.038769
symmetry_mean                0.027390
fractal_dimension_mean       0.007054
radius_se                    0.277069
texture_se                   0.551163
perimeter_se                 2.020077
area_se                     45.451013
smoothness_se                0.003000
compactness_se               0.017892
concavity_se                 0.030160
concave points_se            0.006165
symmetry_se                  0.008259
fractal_dimension_se         0.002644
radius_worst                 4.828993
texture_worst                6.140854
perimeter_worst             33.573002
area_worst                 568.856459
smoothness_worst             0.022812
compactness_

In [10]:
from sklearn import preprocessing

In [38]:
X = df.drop('diagnosis', axis=1)
X.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [39]:
scaler = preprocessing.StandardScaler().fit(X)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [40]:
X = scaler.transform(X)

In [41]:
pca = PCA(n_components=1)
pca.fit(X)
print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

[0.44272026]


In [42]:
pca = PCA(n_components=2)
pca.fit(X)
print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

[0.44272026 0.63243208]


In [43]:
pca = PCA(n_components=3)
pca.fit(X)
print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

[0.44272026 0.63243208 0.72636371]


In [44]:
pca = PCA(n_components=4)
pca.fit(X)
print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

[0.44272026 0.63243208 0.72636371 0.79238506]


In [45]:
pca = PCA(n_components=5)
pca.fit(X)
print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

[0.44272026 0.63243208 0.72636371 0.79238506 0.84734274]


In [46]:
pca = PCA(n_components=6)
pca.fit(X)
print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

[0.44272026 0.63243208 0.72636371 0.79238506 0.84734274 0.88758796]


In [48]:
pca = PCA(n_components=7)
pca.fit(X)
print(pca.explained_variance_ratio_.cumsum())
# print(pca.singular_values_)

[0.44272026 0.63243208 0.72636371 0.79238506 0.84734274 0.88758796
 0.9100953 ]


In [49]:
d2 = pca.fit_transform(X)
X2 = pd.DataFrame(d2, columns = ['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7'])
X2.head()

PC1        PC2       PC3       PC4       PC5       PC6       PC7
0  9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159380
1  2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013365
2  5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668161
3  7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053423  1.429889
4  3.935302  -1.948072  1.389767  2.940639  0.546748 -1.226493 -0.936239

In [50]:
df2 = pd.concat([X2, df['diagnosis']], axis=1)
df2.head()

PC1        PC2       PC3       PC4       PC5       PC6       PC7  \
0  9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159380   
1  2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013365   
2  5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668161   
3  7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053423  1.429889   
4  3.935302  -1.948072  1.389767  2.940639  0.546748 -1.226493 -0.936239   

   diagnosis  
0          0  
1          0  
2          0  
3          0  
4          0

In [51]:
df2['diagnosis'].value_counts()

1    357
0    212
Name: diagnosis, dtype: int64

In [52]:
df2.columns

Index(['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7', 'diagnosis'], dtype='object')

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

features = ['PC1', 'PC2', 'PC3', 'PC4', 'PC5', 'PC6', 'PC7']
target = ['diagnosis']
X = df2[features]
Y = df2[target]
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial').fit(X_train, y_train)
clf.predict(X_test)
clf.predict_proba(X_test) 
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

0.9758241758241758
0.9824561403508771


c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1. What is the second principal component of PCA tell us about?

As there are as many principal components as there are variables in the data, principal components are constructed in such a manner that the first principal component accounts for the largest possible variance in the data set. For example, let’s assume that the scatter plot of our data set is as shown below, can we guess the first principal component ? Yes, it’s approximately the line that matches the purple marks because it goes through the origin and it’s the line in which the projection of the points (red dots) is the most spread out. Or mathematically speaking, it’s the line that maximizes the variance (the average of the squared distances from the projected points (red dots) to the origin).

The second principal component is calculated in the same way, with the condition that it is uncorrelated with (i.e., perpendicular to) the first principal component and that it accounts for the next highest variance.
This continues until a total of p principal components have been calculated, equal to the original number of variables.

2. What is the disadvantage of PCA? 

PCA doesn’t have any disadvantages. If used correctly, it should filter out the noise, and you should be left with a stronger signal.

However, a related question is, what are the limitations of PCA, that is, when can you apply PCA on a dataset for dimensionality reduction. For this, we need to know about the assumptions that are used in PCA:

Linearity : PCA assumes that the principle components are a linear combination of the original features. If this is not true, PCA will not give you sensible results.
Large variance implies more structure : PCA uses variance as the measure of how important a particular dimension is. So, high variance axes are treated as principle components, while low variance axes are treated as noise.
Orthogonality : PCA assumes that the principle components are orthogonal.

3. When we use the L1 vs L2 regularization?

A regression model that uses L1 regularization technique is called Lasso Regression and model which uses L2 is called Ridge Regression.

The key difference between these two is the penalty term.

Ridge regression adds “squared magnitude” of coefficient as penalty term to the loss function. Here the highlighted part represents L2 regularization element.

Here, if lambda is zero then you can imagine we get back OLS. However, if lambda is very large then it will add too much weight and it will lead to under-fitting. Having said that it’s important how lambda is chosen. This technique works very well to avoid over-fitting issue.

Lasso Regression (Least Absolute Shrinkage and Selection Operator) adds “absolute value of magnitude” of coefficient as penalty term to the loss function.

Again, if lambda is zero then we will get back OLS whereas very large value will make coefficients zero hence it will under-fit.

The key difference between these techniques is that Lasso shrinks the less important feature’s coefficient to zero thus, removing some feature altogether. So, this works well for feature selection in case we have a huge number of features.

Traditional methods like cross-validation, stepwise regression to handle overfitting and perform feature selection work well with a small set of features but these techniques are a great alternative when we are dealing with a large set of features.