In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv('train.csv')
df_train.head()

id                species   margin1   margin2   margin3   margin4  \
0   1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906   
1   2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625   
2   3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812   
3   5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859   
4   6     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766   

    margin5   margin6   margin7  margin8  ...  texture55  texture56  \
0  0.011719  0.009766  0.027344      0.0  ...   0.007812   0.000000   
1  0.025391  0.001953  0.019531      0.0  ...   0.000977   0.000000   
2  0.003906  0.005859  0.068359      0.0  ...   0.154300   0.000000   
3  0.021484  0.019531  0.023438      0.0  ...   0.000000   0.000977   
4  0.013672  0.015625  0.005859      0.0  ...   0.096680   0.000000   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156        0.0        0.0   0.004883   
1   0.000000   0.000977   0.023438        0.0        0.0   0.000977   
2   0.005859   0.000977   0.007812        0.0        0.0   0.000000   
3   0.000000   0.000000   0.020508        0.0        0.0   0.017578   
4   0.021484   0.000000   0.000000        0.0        0.0   0.000000   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  
4   0.000000   0.031250  

[5 rows x 194 columns]

In [3]:
df_test = pd.read_csv('test.csv')
df_test.head()

id   margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0   4  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   
1   7  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812   
2   9  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000  0.023438   
3  12  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000  0.003906   
4  13  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000  0.009766   

   margin8   margin9  ...  texture55  texture56  texture57  texture58  \
0      0.0  0.005859  ...   0.006836   0.000000   0.015625   0.000977   
1      0.0  0.033203  ...   0.000000   0.000000   0.006836   0.001953   
2      0.0  0.011719  ...   0.128910   0.000000   0.000977   0.000000   
3      0.0  0.003906  ...   0.012695   0.015625   0.002930   0.036133   
4      0.0  0.005859  ...   0.000000   0.042969   0.016602   0.010742   

   texture59  texture60  texture61  texture62  texture63  texture64  
0   0.015625        0.0        0.0   0.000000   0.003906   0.053711  
1   0.013672        0.0        0.0   0.000977   0.037109   0.044922  
2   0.000000        0.0        0.0   0.015625   0.000000   0.000000  
3   0.013672        0.0        0.0   0.089844   0.000000   0.008789  
4   0.041016        0.0        0.0   0.007812   0.009766   0.007812  

[5 rows x 193 columns]

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Columns: 194 entries, id to texture64
dtypes: float64(192), int64(1), object(1)
memory usage: 1.5+ MB


In [5]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Columns: 193 entries, id to texture64
dtypes: float64(192), int64(1)
memory usage: 895.7 KB


In [6]:
train = df_train.drop(['id'], axis = 1)
train.head()

species   margin1   margin2   margin3   margin4   margin5  \
0            Acer_Opalus  0.007812  0.023438  0.023438  0.003906  0.011719   
1  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625  0.025391   
2   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812  0.003906   
3        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859  0.021484   
4     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766  0.013672   

    margin6   margin7  margin8   margin9  ...  texture55  texture56  \
0  0.009766  0.027344      0.0  0.001953  ...   0.007812   0.000000   
1  0.001953  0.019531      0.0  0.000000  ...   0.000977   0.000000   
2  0.005859  0.068359      0.0  0.000000  ...   0.154300   0.000000   
3  0.019531  0.023438      0.0  0.013672  ...   0.000000   0.000977   
4  0.015625  0.005859      0.0  0.000000  ...   0.096680   0.000000   

   texture57  texture58  texture59  texture60  texture61  texture62  \
0   0.002930   0.002930   0.035156        0.0        0.0   0.004883   
1   0.000000   0.000977   0.023438        0.0        0.0   0.000977   
2   0.005859   0.000977   0.007812        0.0        0.0   0.000000   
3   0.000000   0.000000   0.020508        0.0        0.0   0.017578   
4   0.021484   0.000000   0.000000        0.0        0.0   0.000000   

   texture63  texture64  
0   0.000000   0.025391  
1   0.039062   0.022461  
2   0.020508   0.002930  
3   0.000000   0.047852  
4   0.000000   0.031250  

[5 rows x 193 columns]

In [7]:
X = train.iloc[:, 1:]
y = train['species']

In [8]:
test = df_test.drop('id', axis = 1)
test.head()

margin1   margin2   margin3   margin4   margin5   margin6   margin7  \
0  0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859   
1  0.007812  0.005859  0.064453  0.009766  0.003906  0.013672  0.007812   
2  0.000000  0.000000  0.001953  0.021484  0.041016  0.000000  0.023438   
3  0.000000  0.000000  0.009766  0.011719  0.017578  0.000000  0.003906   
4  0.001953  0.000000  0.015625  0.009766  0.039062  0.000000  0.009766   

   margin8   margin9  margin10  ...  texture55  texture56  texture57  \
0      0.0  0.005859  0.023438  ...   0.006836   0.000000   0.015625   
1      0.0  0.033203  0.023438  ...   0.000000   0.000000   0.006836   
2      0.0  0.011719  0.005859  ...   0.128910   0.000000   0.000977   
3      0.0  0.003906  0.001953  ...   0.012695   0.015625   0.002930   
4      0.0  0.005859  0.000000  ...   0.000000   0.042969   0.016602   

   texture58  texture59  texture60  texture61  texture62  texture63  texture64  
0   0.000977   0.015625        0.0        0.0   0.000000   0.003906   0.053711  
1   0.001953   0.013672        0.0        0.0   0.000977   0.037109   0.044922  
2   0.000000   0.000000        0.0        0.0   0.015625   0.000000   0.000000  
3   0.036133   0.013672        0.0        0.0   0.089844   0.000000   0.008789  
4   0.010742   0.041016        0.0        0.0   0.007812   0.009766   0.007812  

[5 rows x 192 columns]

In [9]:
from sklearn.preprocessing import StandardScaler

X = StandardScaler().fit_transform(X)
X

array([[-0.48661074, -0.13135701, -0.33095592, ..., -0.39487147,
        -0.65214311,  0.26239707],
       [-0.58560191, -0.73488047, -0.02856115, ..., -0.49497401,
         2.18166976,  0.13364087],
       [-0.58560191, -0.48340807, -0.48219201, ..., -0.52001246,
         0.83564129, -0.72463124],
       ...,
       [-0.78358426, -0.63430181, -1.23821765, ...,  0.1807566 ,
        -0.65214311, -0.76756462],
       [-0.88257543, -0.73488047,  0.5762671 , ..., -0.52001246,
        -0.51045972, -0.72463124],
       [ 0.30542003, -0.23196142, -0.02856115, ...,  0.08065405,
         1.18988604,  0.13364087]])

In [10]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
y = le.fit_transform(y.values)
y

array([ 3, 49, 65, 94, 84, 40, 54, 78, 53, 89, 98, 16, 74, 50, 58, 31, 43,
        4, 75, 44, 83, 84, 13, 66, 15,  6, 73, 22, 73, 31, 36, 27, 94, 88,
       12, 28, 21, 25, 20, 60, 84, 65, 69, 58, 23, 76, 18, 52, 54,  9, 48,
       47, 64, 81, 83, 36, 58, 21, 81, 20, 62, 88, 34, 92, 79, 82, 20, 32,
        4, 84, 36, 35, 72, 60, 71, 72, 52, 50, 54, 11, 51, 18, 47,  5,  8,
       37, 97, 20, 33,  1, 59,  1, 56,  1,  9, 57, 20, 79, 29, 16, 32, 54,
       93, 10, 46, 59, 84, 76, 15, 10, 15,  0, 69,  4, 51, 51, 94, 36, 39,
       62,  2, 24, 26, 35, 25, 87,  0, 55, 34, 38,  1, 45,  7, 93, 56, 38,
       21, 51, 75, 81, 74, 33, 20, 37,  9, 40, 60, 31, 83, 50, 71, 67, 30,
       66,  1, 43, 61, 23, 65, 84, 87, 46, 57, 16,  2, 28, 12, 96, 44, 76,
       29, 75, 41, 87, 67, 61, 30,  5, 12, 62,  3, 83, 81,  6, 85,  4, 37,
       57, 84, 39, 71, 61,  6, 76, 14, 31, 98, 40, 17, 51, 16, 42, 63, 86,
       37, 69, 86, 71, 80, 78, 14, 35, 25,  5, 39,  8,  9, 26, 44, 60, 13,
       14, 77, 13, 80, 87

In [11]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089])

In [12]:
pca = PCA(n_components=2)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089, 0.34569641])

In [13]:
pca = PCA(n_components=5)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089, 0.34569641, 0.40841733, 0.46477469, 0.50676319])

In [14]:
pca = PCA(n_components=15)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089, 0.34569641, 0.40841733, 0.46477469, 0.50676319,
       0.54192255, 0.57285348, 0.60075988, 0.62569693, 0.64708818,
       0.66436386, 0.6812748 , 0.6970458 , 0.7116475 , 0.72444746])

In [15]:
pca = PCA(n_components=20)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089, 0.34569641, 0.40841733, 0.46477469, 0.50676319,
       0.54192255, 0.57285347, 0.60075988, 0.62569687, 0.64708808,
       0.66436262, 0.68127343, 0.69704438, 0.71164433, 0.72443983,
       0.73680686, 0.74799805, 0.75851216, 0.7680343 , 0.77732404])

In [16]:
pca = PCA(n_components=30)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089, 0.34569641, 0.40841733, 0.46477469, 0.50676319,
       0.54192255, 0.57285348, 0.60075988, 0.62569692, 0.64708817,
       0.66436386, 0.68127481, 0.69704579, 0.71164752, 0.72444722,
       0.73681474, 0.74800969, 0.7585366 , 0.76809049, 0.77742458,
       0.78595489, 0.79412194, 0.8018999 , 0.80939838, 0.81608812,
       0.82242911, 0.82854819, 0.8344278 , 0.83996918, 0.84526089])

In [17]:
pca = PCA(n_components=40)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089, 0.34569641, 0.40841733, 0.46477469, 0.50676319,
       0.54192255, 0.57285348, 0.60075988, 0.62569693, 0.64708818,
       0.66436388, 0.68127484, 0.69704585, 0.71164759, 0.72444757,
       0.73681523, 0.74801033, 0.75853736, 0.76809161, 0.77742696,
       0.78595984, 0.79412792, 0.80190782, 0.80941804, 0.81611408,
       0.82247876, 0.82860275, 0.83449869, 0.84006955, 0.8453808 ,
       0.85044133, 0.85531307, 0.85996648, 0.86456259, 0.86899353,
       0.87319514, 0.87717742, 0.88098829, 0.88456355, 0.88794042])

In [18]:
pca = PCA(n_components=44)
clf = pca.fit_transform(X)
pca.explained_variance_ratio_.cumsum()

array([0.24158089, 0.34569641, 0.40841733, 0.46477469, 0.50676319,
       0.54192255, 0.57285348, 0.60075988, 0.62569693, 0.64708818,
       0.66436388, 0.68127485, 0.69704585, 0.71164759, 0.72444757,
       0.73681523, 0.74801034, 0.75853739, 0.76809165, 0.77742703,
       0.78595991, 0.79412802, 0.80190835, 0.80941872, 0.816116  ,
       0.82248067, 0.82860715, 0.8345038 , 0.84007566, 0.84538802,
       0.85045727, 0.8553513 , 0.86000364, 0.86460052, 0.86903128,
       0.87322706, 0.87721506, 0.88102501, 0.88461531, 0.88800504,
       0.8913623 , 0.89460195, 0.89763466, 0.90047462])

In [19]:
clf = pd.DataFrame(clf)
clf.head()

0         1         2         3         4         5         6   \
0 -3.602928  1.184124 -0.287910 -3.375136 -3.034924  1.121179  0.873002   
1  0.456784  5.949279  0.720610 -2.077081  0.305508  2.042332  3.009142   
2  3.768880  1.527634  3.571097  1.318725 -4.118474 -0.917153  1.659270   
3 -3.583156  5.615580 -3.114007 -3.332739 -2.608283  0.369418 -0.479719   
4  3.263170 -0.440329 -5.300400  0.841241 -3.919586 -2.451562 -0.532400   

         7         8         9   ...        34        35        36        37  \
0  0.673270 -0.417717 -0.349668  ... -0.483121  0.566856 -0.378205 -0.870585   
1  0.702168  1.329982  0.117613  ... -1.511891 -0.073765  0.371423  0.560420   
2  1.330377 -3.116156  2.120466  ... -0.218594 -0.284561 -1.839032 -0.100252   
3 -1.712249  0.282203 -1.303736  ... -0.183513  0.537601 -0.671447 -0.901738   
4 -3.411455 -3.609045 -1.505436  ... -0.138634 -0.302923 -1.678308 -1.265850   

         38        39        40        41        42        43  
0 -0.952219 -0.988755 -0.652745 -0.788245 -1.015372  0.496776  
1  0.229911  0.796735  0.205132  1.299155  1.298739  0.707736  
2  1.265535  1.889688  0.505690  2.547453  1.527711  0.079880  
3  0.380277  0.326761  0.027447 -0.026483  0.250288 -0.727557  
4 -0.891103  0.016269  0.038451 -0.361487  0.012682  0.360722  

[5 rows x 44 columns]

In [20]:
X = clf

In [21]:
X.corr()

0             1             2             3             4   \
0   1.000000e+00 -2.010103e-17 -4.465995e-17 -2.562933e-18 -1.099552e-17   
1  -2.010103e-17  1.000000e+00 -8.961826e-16 -2.684006e-17 -1.731968e-16   
2  -4.465995e-17 -8.961826e-16  1.000000e+00 -1.751046e-16  2.502581e-16   
3  -2.562933e-18 -2.684006e-17 -1.751046e-16  1.000000e+00  3.876809e-16   
4  -1.099552e-17 -1.731968e-16  2.502581e-16  3.876809e-16  1.000000e+00   
5  -5.488327e-17 -1.110180e-16  1.808471e-16  4.175734e-16  5.806996e-16   
6   1.129750e-17  4.677928e-17 -2.859038e-17  1.144900e-16 -1.637915e-16   
7   3.699082e-17 -3.622434e-17  8.097364e-18 -5.153655e-16  2.924266e-16   
8  -2.524716e-17 -1.499516e-16  7.913121e-17  1.157928e-16 -2.721454e-16   
9  -2.242505e-18  6.675885e-17 -7.079986e-18  3.235227e-16 -2.360513e-16   
10 -9.301557e-17  5.839344e-18  4.343713e-17 -1.227961e-16  2.167789e-16   
11 -1.103889e-17  7.806204e-17 -2.647096e-17 -4.480186e-17 -7.636644e-17   
12  1.211219e-17  5.389417e-17  3.272230e-17 -2.617431e-17  1.787205e-16   
13  3.482300e-17  1.842923e-17  8.987693e-17  1.379449e-17 -5.513888e-18   
14  3.709869e-17 -3.283135e-17  5.516315e-17 -5.201816e-17  2.338040e-17   
15  2.272292e-17  4.700979e-18  3.617013e-17  4.077370e-17  1.199497e-16   
16  1.393518e-17 -1.377630e-17  1.093206e-16 -2.911892e-17  1.059408e-17   
17  5.327790e-19 -4.103671e-17 -1.454770e-16 -6.685564e-17  8.628927e-17   
18  3.122043e-17  6.944624e-19 -2.042409e-17 -6.473973e-17  7.815285e-18   
19 -3.508960e-17  1.896201e-17  1.227720e-16  1.068229e-16 -4.403085e-17   
20 -2.866222e-17  4.614866e-17 -1.060398e-16  9.737709e-17 -6.504760e-17   
21  4.786115e-17 -1.488141e-17 -1.599921e-17  9.724094e-17 -1.053402e-17   
22  4.270736e-17  1.465262e-17  1.454224e-17 -3.369507e-17 -2.788819e-17   
23  2.961868e-17  2.322684e-17 -3.923688e-17  8.289927e-17 -9.454537e-17   
24  3.848036e-18  2.326373e-17  4.807656e-17 -1.839927e-17  7.488550e-18   
25 -2.234323e-17 -5.058663e-17 -6.922477e-17  8.672136e-17 -9.857631e-17   
26 -3.555690e-17 -1.304337e-17  1.168014e-17  9.027707e-17  1.922813e-17   
27  1.764187e-17  4.101687e-18  2.551197e-18 -1.896782e-17 -1.069051e-17   
28  6.893351e-17 -5.381128e-17 -2.690114e-17  1.318434e-19 -5.766144e-17   
29 -4.019794e-17 -9.493358e-18 -2.212667e-17 -1.313120e-17 -3.421944e-17   
30  5.751567e-17 -4.894126e-17  1.113717e-17  4.658186e-17  6.261433e-17   
31 -5.028062e-18  4.240933e-17  1.200153e-17  7.737268e-19 -5.830619e-17   
32  1.843285e-17  7.043384e-17 -1.347188e-17 -8.310848e-17  8.107271e-17   
33  1.444235e-17  2.452243e-17  5.221648e-17  7.431846e-17  6.848539e-17   
34  1.492484e-17 -5.629209e-17 -7.820288e-17 -4.243277e-17 -5.472685e-17   
35  3.676495e-17  9.199614e-17 -6.920137e-17 -8.310737e-17  4.224483e-18   
36 -1.667241e-17 -4.192125e-17  3.146512e-17  8.742661e-17 -5.741402e-17   
37 -2.438366e-17  3.527238e-17 -2.307895e-17  1.206318e-16  2.776253e-17   
38 -4.656670e-17 -7.613679e-17  5.807260e-17 -5.420100e-18  5.565822e-17   
39  2.557470e-17 -6.653450e-17 -1.056318e-16 -4.115992e-17  4.367073e-17   
40 -1.886853e-18 -7.260391e-17 -1.610035e-17  5.537120e-17  2.066168e-18   
41 -5.002422e-17 -1.575040e-17 -3.314875e-17  1.798220e-17  8.213031e-17   
42 -7.060578e-17 -9.450142e-17  1.736344e-18  8.846024e-18  1.009317e-17   
43  5.978377e-17  8.738068e-18 -6.888367e-17 -3.010163e-17  6.003976e-17   

              5             6             7             8             9   ...  \
0  -5.488327e-17  1.129750e-17  3.699082e-17 -2.524716e-17 -2.242505e-18  ...   
1  -1.110180e-16  4.677928e-17 -3.622434e-17 -1.499516e-16  6.675885e-17  ...   
2   1.808471e-16 -2.859038e-17  8.097364e-18  7.913121e-17 -7.079986e-18  ...   
3   4.175734e-16  1.144900e-16 -5.153655e-16  1.157928e-16  3.235227e-16  ...   
4   5.806996e-16 -1.637915e-16  2.924266e-16 -2.721454e-16 -2.360513e-16  ...   
5   1.000000e+00 -1.488480e-16  8.025529e-17  2.352281e-16  4.602033e-16  ...   
6  -1.488480e-16  1.000000

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
from sklearn import tree

clf1 = tree.DecisionTreeClassifier()
clf1 = clf1.fit(X_train, y_train)

In [24]:
clf1.score(X_train, y_train)

1.0

In [25]:
clf1.score(X_test, y_test)

0.6515151515151515

In [26]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, max_depth=4)
clf = clf.fit(X_train, y_train)

In [27]:
clf.score(X_train, y_train)

0.8282828282828283

In [28]:
clf.score(X_test, y_test)

0.5656565656565656

In [29]:
from sklearn.svm import SVC
clf4 = SVC(kernel='rbf', gamma='auto')
clf4 = clf4.fit(X_train, y_train)

print(clf4.score(X_train, y_train))
print(clf4.score(X_test, y_test))

1.0
0.9494949494949495


In [36]:
clf5 = SVC(kernel='poly', gamma='auto')
clf5 = clf5.fit(X_train, y_train)

print(clf5.score(X_train, y_train))
print(clf5.score(X_test, y_test))

1.0
0.9595959595959596


In [30]:
from sklearn.svm import LinearSVC

clf2 = LinearSVC(random_state=0, tol=1e-5)
clf2 = clf2.fit(X_train, y_train)

c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [31]:
clf2.score(X_train, y_train)

1.0

In [32]:
clf2.score(X_test, y_test)

0.98989898989899

In [33]:
from sklearn.naive_bayes import GaussianNB

clf3 = GaussianNB()
clf3 = clf3.fit(X_train, y_train)

In [34]:
clf3.score(X_train, y_train)

1.0

In [35]:
clf3.score(X_test, y_test)

0.9292929292929293

Linear SVM is the best fit for this dataset. 