In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Part 1: Naive bayes

1. Load the kinematics dataset as measured on mobile sensors from the file “run_or_walk.csv”. List out the columns in the dataset.

In [2]:
df1 = pd.read_csv('run_or_walk.csv')
df1.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [4]:
df1.columns

Index(['date', 'time', 'username', 'wrist', 'activity', 'acceleration_x',
       'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

2. Let the target variable ‘y’ be the activity and assign all the columns after it to ‘x’.

In [18]:
target = ['activity']
features = ['acceleration_x', 'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z']

x = df1[features]
y = df1[target]

In [6]:
x.head()

acceleration_x  acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z
0          0.2650         -0.7814         -0.0076 -0.0590  0.0325 -2.9296
1          0.6722         -1.1233         -0.2344 -0.1757  0.0208  0.1269
2          0.4399         -1.4817          0.0722 -0.9105  0.1063 -2.4367
3          0.3031         -0.8125          0.0888  0.1199 -0.4099 -2.9336
4          0.4814         -0.9312          0.0359  0.0527  0.4379  2.4922

In [7]:
y.head()

activity
0         0
1         0
2         0
3         0
4         0

3. Using Scikit-learn fit a Gaussian Naive Bayes model and observe the accuracy. Generate a classification report using scikit learn.

In [8]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(x, y)

c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [21]:
clf_pf = GaussianNB()
clf_pf.partial_fit(x, y, np.unique(y))

c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [142]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)
clf1 = GaussianNB()
model = clf1.fit(X_train, y_train)
pred = model.predict(X_test)

print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

0.9571327783265133
0.958911841065583


c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [36]:
from sklearn.metrics import classification_report, confusion_matrix

print('Naive Bayes Classifier')
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

Naive Bayes Classifier
[[8828   85]
 [ 659 8146]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      8913
           1       0.99      0.93      0.96      8805

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



4. Repeat the model once using only the acceleration values as predictors and then using only the gyro values as predictors. Comment on the difference in accuracy between both the models.

In [37]:
target = ['activity']
features = ['acceleration_x', 'acceleration_y', 'acceleration_z']

x = df1[features]
y = df1[target]

In [38]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)
clf1 = GaussianNB()
model = clf1.fit(X_train, y_train)
pred = model.predict(X_test)

print(model.score(X_train, y_train))
print(model.score(X_test, y_test))

0.9571327783265133
0.958911841065583


c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [39]:
print('Naive Bayes Classifier')
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

Naive Bayes Classifier
[[8859   54]
 [ 674 8131]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      8913
           1       0.99      0.92      0.96      8805

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



## Part 2: SVM

1. Load the data from “college.csv” that has attributes collected about private and public colleges for a particular year. We will try to predict the private/public status of the college from other attributes.

In [101]:
df2 = pd.read_csv('college.csv')
df2.head()

Private  Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0     Yes  1660    1232     721         23         52         2885   
1     Yes  2186    1924     512         16         29         2683   
2     Yes  1428    1097     336         22         50         1036   
3     Yes   417     349     137         60         89          510   
4     Yes   193     146      55         16         44          249   

   P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0          537      7440        3300    450      2200   70        78   
1         1227     12280        6450    750      1500   29        30   
2           99     11250        3750    400      1165   53        66   
3           63     12960        5450    450       875   92        97   
4          869      7560        4120    800      1500   76        72   

   S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0       18.1           12    7041         60  
1       12.2           16   10527         56  
2       12.9           30    8735         54  
3        7.7           37   19016         59  
4       11.9            2   10922         15

2. Use LabelEncoder to encode the target variable in to numerical form and split the data such that 20% of the data is set aside for testing.

In [61]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(Y)
Y = le.transform(Y)

In [102]:
df2['Private'].value_counts()

Yes    565
No     212
Name: Private, dtype: int64

In [103]:
d = {'Private': {'No': 0, 'Yes': 1}}
df2.replace(d, inplace=True)
df2.head()

Private  Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0        1  1660    1232     721         23         52         2885   
1        1  2186    1924     512         16         29         2683   
2        1  1428    1097     336         22         50         1036   
3        1   417     349     137         60         89          510   
4        1   193     146      55         16         44          249   

   P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0          537      7440        3300    450      2200   70        78   
1         1227     12280        6450    750      1500   29        30   
2           99     11250        3750    400      1165   53        66   
3           63     12960        5450    450       875   92        97   
4          869      7560        4120    800      1500   76        72   

   S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0       18.1           12    7041         60  
1       12.2           16   10527         56  
2       12.9           30    8735         54  
3        7.7           37   19016         59  
4       11.9            2   10922         15

In [144]:
df2.columns

Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')

In [145]:
features = ['Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc', 
            'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 
            'Books', 'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 
            'perc.alumni', 'Expend', 'Grad.Rate']
target = ['Private']

X = df2[features]
Y = df2[target]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

3. Fit a linear svm from scikit learn and observe the accuracy. [Hint: Use Linear SVC]

In [52]:
from sklearn.svm import LinearSVC
# from sklearn.datasets import make_classification

In [146]:
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(X_train, y_train)
model = clf.fit(X_train, y_train)
pred = model.predict(X_test)
print('Accuracy of training set:\t', clf.score(X_train, y_train))
print('Accuracy of test set:\t', clf.score(X_test, y_test))

Accuracy of training set:	 0.9404186795491143
Accuracy of test set:	 0.9294871794871795


c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed t

In [147]:
print(clf.coef_)
print(clf.intercept_)

[[-3.55461817e-05  4.60642133e-05  9.71764653e-06  1.78813856e-03
   1.10321458e-03 -2.46859982e-04 -1.77872073e-04  2.67314049e-04
  -5.20686475e-05  3.01193338e-04 -2.58016801e-04 -5.23549770e-03
  -5.81928236e-03 -1.21772865e-03  7.07926640e-04 -4.57630451e-06
   9.70311071e-04]]
[-4.5533586e-05]


In [148]:
print('Support Vector Machine')
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

Support Vector Machine
[[ 44   3]
 [  8 101]]
              precision    recall  f1-score   support

           0       0.85      0.94      0.89        47
           1       0.97      0.93      0.95       109

    accuracy                           0.93       156
   macro avg       0.91      0.93      0.92       156
weighted avg       0.93      0.93      0.93       156



4. Preprocess the data using StandardScalar and fit the same model again and observe the change in accuracy.
[Hint: Refer to scikitlearn’s preprocessing methods]

In [62]:
from sklearn.preprocessing import StandardScaler

In [149]:
X = df2[features]
Y = df2[target]

scaler = StandardScaler()
scaler = scaler.fit(X)

X = scaler.transform(X)

X = pd.DataFrame(X)

# X = StandardScaler().fit_transform(X.values)

In [150]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [151]:
print('Accuracy of training set:\t', clf.score(X_train, y_train))
print('Accuracy of test set:\t', clf.score(X_test, y_test))

Accuracy of training set:	 0.6022544283413849
Accuracy of test set:	 0.5833333333333334


In [152]:
pred = model.predict(X_test)
print('Support Vector Machine with StandardScalar')
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

Support Vector Machine with StandardScalar
[[35 12]
 [53 56]]
              precision    recall  f1-score   support

           0       0.40      0.74      0.52        47
           1       0.82      0.51      0.63       109

    accuracy                           0.58       156
   macro avg       0.61      0.63      0.58       156
weighted avg       0.70      0.58      0.60       156



In [157]:
clf1 = LinearSVC(random_state=0, tol=1e-5)
clf1 = clf1.fit(X_train, y_train)
y_pred = clf1.predict(X_test)
print('Accuracy of training set:\t', clf1.score(X_train, y_train))
print('Accuracy of test set:\t', clf1.score(X_test, y_test))

Accuracy of training set:	 0.9533011272141707
Accuracy of test set:	 0.9294871794871795


c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [159]:
print('Support Vector Machine new model with StandardScalar')
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Support Vector Machine new model with StandardScalar
[[ 42   5]
 [  6 103]]
              precision    recall  f1-score   support

           0       0.88      0.89      0.88        47
           1       0.95      0.94      0.95       109

    accuracy                           0.93       156
   macro avg       0.91      0.92      0.92       156
weighted avg       0.93      0.93      0.93       156



5. Use scikit learn’s gridsearch to select the best hyperparameter for a non-linear SVM, identify the model with best score and its parameters.
[Hint: Refer to model_selection module of Scikit learn]

In [168]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4], 'C': [1, 10, 100, 1000]}, 
              {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
svc = svm.SVC(gamma="scale")
clf = GridSearchCV(svc, parameters, cv=5)
clf.fit(X_train, y_train)

pd.DataFrame(clf.cv_results_).sort_values('rank_test_score')

c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sk

c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sk

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
4        0.006605  1.024055e-03         0.001401    4.900964e-04     100   
10       0.204341  8.746972e-02         0.000804    4.022958e-04     100   
11       2.533002  1.663267e+00         0.000597    4.877644e-04    1000   
9        0.027022  4.294008e-03         0.000601    4.906412e-04      10   
6        0.007406  8.007288e-04         0.000997    6.585534e-06    1000   
7        0.005003  6.289914e-07         0.001000    9.750824e-06    1000   
8        0.006205  9.804549e-04         0.001001    3.234067e-07       1   
2        0.005200  4.020796e-04         0.001005    6.756296e-06      10   
5        0.005201  3.948928e-04         0.001404    4.879008e-04     100   
0        0.008409  1.029440e-03         0.001802    4.088720e-04       1   
3        0.006604  4.901352e-04         0.001798    3.986691e-04      10   
1        0.008206  9.729126e-04         0.001601    4.902519e-04       1   

   param_gamma param_kernel                                         params  \
4        0.001          rbf    {'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}   
10         NaN       linear                 {'C': 100, 'kernel': 'linear'}   
11         NaN       linear                {'C': 1000, 'kernel': 'linear'}   
9          NaN       linear                  {'C': 10, 'kernel': 'linear'}   
6        0.001          rbf   {'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}   
7       0.0001          rbf  {'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}   
8          NaN       linear                   {'C': 1, 'kernel': 'linear'}   
2        0.001          rbf     {'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}   
5       0.0001          rbf   {'C': 100, 'gamma': 0.0001, 'kernel': 'rbf'}   
0        0.001          rbf      {'C': 1, 'gamma': 0.001, 'kernel': 'rbf'}   
3       0.0001          rbf    {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}   
1       0.0001          rbf     {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}   

    split0_test_score  split1_test_score  split2_test_score  \
4               0.928           0.967742           0.943548   
10              0.928           0.959677           0.943548   
11              0.928           0.959677           0.943548   
9               0.928           0.959677           0.943548   
6               0.928           0.959677           0.935484   
7               0.928           0.959677           0.935484   
8               0.928           0.959677           0.935484   
2               0.896           0.935484           0.903226   
5               0.888           0.935484           0.903226   
0               0.872           0.879032           0.838710   
3               0.872           0.879032           0.838710   
1               0.736           0.733871           0.733871   

    split3_test_score  split4_test_score  mean_test_score  std_test_score  \
4            0.951613           0.967742         0.951691        0.015136   
10           0.959677           0.959677         0.950081        0.012721   
11           0.959677           0.959677         0.950081        0.012721   
9            0.951613           0.959677         0.948470        0.011888   
6            0.959677           0.951613         0.946860        0.012944   
7            0.943548           0.967742         0.946860        0.014816   
8            0.951613           0.959677         0.946860        0.012944   
2            0.935484           0.967742         0.927536        0.025811   
5            0.943548           0.967742         0.927536        0.028622   
0            0.879032           0.895161         0.872786        0.018642   
3            0.879032           0.895161         0.872786        0.018642   
1            0.733871           0.733871         0.734300        0.000854   

    rank_test_score  
4                 1  
10                2  
11                2  
9                 4  
6                 5  
7                 5  
8                 5  
2 

In [169]:
pd.DataFrame(clf.cv_results_).sort_values('rank_test_score')['params'].iloc[0]

{'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}

## Project: Domain Media

In [170]:
df3 = pd.read_csv('voice-classification.csv')
df3.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [171]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
meanfreq    3168 non-null float64
sd          3168 non-null float64
median      3168 non-null float64
Q25         3168 non-null float64
Q75         3168 non-null float64
IQR         3168 non-null float64
skew        3168 non-null float64
kurt        3168 non-null float64
sp.ent      3168 non-null float64
sfm         3168 non-null float64
mode        3168 non-null float64
centroid    3168 non-null float64
meanfun     3168 non-null float64
minfun      3168 non-null float64
maxfun      3168 non-null float64
meandom     3168 non-null float64
mindom      3168 non-null float64
maxdom      3168 non-null float64
dfrange     3168 non-null float64
modindx     3168 non-null float64
label       3168 non-null object
dtypes: float64(20), object(1)
memory usage: 507.4+ KB


In [172]:
df3.columns

Index(['meanfreq', 'sd', 'median', 'Q25', 'Q75', 'IQR', 'skew', 'kurt',
       'sp.ent', 'sfm', 'mode', 'centroid', 'meanfun', 'minfun', 'maxfun',
       'meandom', 'mindom', 'maxdom', 'dfrange', 'modindx', 'label'],
      dtype='object')

In [174]:
X = df3.iloc[:, :-1]
Y = df3.iloc[:, -1]

In [176]:
Y.value_counts()

male      1584
female    1584
Name: label, dtype: int64

In [177]:
le = preprocessing.LabelEncoder()
le.fit(Y.values)
Y = le.transform(Y)
X = X.values

In [178]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [180]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
clf = clf.fit(X_train, y_train)

print('Score of training: \t', clf.score(X_train, y_train))
print('Score of test: \t', clf.score(X_test, y_test))

Score of training: 	 0.8046566692975533
Score of test: 	 0.8107255520504731


c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [181]:
y_pred = clf.predict(X_test)
print('Logistic Regression')
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Logistic Regression
[[240  57]
 [ 63 274]]
              precision    recall  f1-score   support

           0       0.79      0.81      0.80       297
           1       0.83      0.81      0.82       337

    accuracy                           0.81       634
   macro avg       0.81      0.81      0.81       634
weighted avg       0.81      0.81      0.81       634

