In [13]:
import numpy as np

In [14]:
m = np.matrix([[0.8, 0.2], [0.7, 0.3]])

In [15]:
np.linalg.matrix_power(m, 2)

matrix([[0.78, 0.22],
        [0.77, 0.23]])

In [16]:
np.linalg.matrix_power(m, 3)

matrix([[0.778, 0.222],
        [0.777, 0.223]])

In [17]:
np.linalg.matrix_power(m, 4)

matrix([[0.7778, 0.2222],
        [0.7777, 0.2223]])

In [18]:
np.linalg.matrix_power(m, 5)

matrix([[0.77778, 0.22222],
        [0.77777, 0.22223]])

In [19]:
np.linalg.matrix_power(m, 6)

matrix([[0.777778, 0.222222],
        [0.777777, 0.222223]])

In [20]:
np.linalg.matrix_power(m, 7)

matrix([[0.7777778, 0.2222222],
        [0.7777777, 0.2222223]])

In [21]:
np.linalg.matrix_power(m, 8)

matrix([[0.77777778, 0.22222222],
        [0.77777777, 0.22222223]])

In [22]:
np.linalg.matrix_power(m, 9)

matrix([[0.77777778, 0.22222222],
        [0.77777778, 0.22222222]])