In [21]:
import numpy as np
# R matrix
R = np.matrix([ [-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100] ])
print(R)

[[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [ -1   0   0  -1  -1 100]
 [ -1   0  -1  -1   0 100]]


In [24]:
# Q matrix
Q = np.matrix (np.zeros([6,6]))
print(Q)
# Gamma (learning parameter)
gamma = 0.8
# Initial state (Usually to be chosen at random)
initial_state = 1

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
# This function returns all available actions in the state given as # an argument
def available_actions(state):
    current_state_row = R[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act
# Get available actions in the current state
available_act = available_actions(initial_state)
print('Possible action:')
print(available_act)
# This function chooses at random which action to be performed within the range of all the available actions
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_act,1))
    return next_action
# Sample next action to be performed
action = sample_next_action(available_act)
print('Action:')
print(action)

Possible action:
[3 5]
Action:
3


In [26]:
# This function updates the Q matrix according to the path selected and the Q learning algorithm
def update(current_state, action, gamma):  
    print(Q[action,])
    print(np.max(Q[action,]))
    max_index = np.where(Q[action,] == np.max(Q[action,]))[1]
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index, size = 1))
        print('max index > 1: ' + str(max_index))
    else:
        max_index = int(max_index)
        print('max index: ' + str(max_index))
    max_value = Q[action, max_index] 
    print('max_value: ' + str(max_value))
    Q[current_state, action] = R[current_state, action] + gamma * max_value
update(initial_state,action,gamma)
print(Q)

[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 5
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [27]:
# Train over 10 000 iterations(Re-iterate the # process above)
for i in range(10000):
    current_state = np.random.randint(0, int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_action(available_act)
    update(current_state,action,gamma)
print(Q)

[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 4
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 4
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 4
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 5
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 5
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 1
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 0
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 3
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 0
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 5
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 5
max_value: 0.0
[[  0.   0.   0.   0.   0. 100.]]
100.0
max index: 5
max_value: 100.0
[[  0.   0.   0.   0.   0. 100.]]
100.0
max index: 5
max_value: 100.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 1
max_value: 0.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index > 1: 2
max_value: 0.0
[[  0.   0.   0.   0.   0. 100.]]
100.0
max index: 5
max_value: 100.0
[[0. 0. 0. 0. 0. 0.]]
0.0
max index 

  457.05032704]]
457.05032704000007
max index: 5
max_value: 457.05032704000007
[[  0.         365.64026163   0.           0.         346.3129088
  465.64026163]]
465.6402616320001
max index: 5
max_value: 465.6402616320001
[[  0.         365.64026163 228.51220931   0.         357.05032704
    0.        ]]
365.6402616320001
max index: 1
max_value: 365.6402616320001
[[  0.           0.           0.         292.51220931   0.
    0.        ]]
292.5122093056001
max index: 3
max_value: 292.5122093056001
[[  0.         365.64026163 234.00976744   0.         357.05032704
    0.        ]]
365.6402616320001
max index: 1
max_value: 365.6402616320001
[[  0.           0.           0.         285.64026163   0.
  457.05032704]]
457.05032704000007
max index: 5
max_value: 457.05032704000007
[[  0.           0.           0.         292.51220931   0.
    0.        ]]
292.5122093056001
max index: 3
max_value: 292.5122093056001
[[  0.         365.64026163   0.           0.         346.3129088
  465.64026163

  495.38831398]]
495.3883139815727
max index: 5
max_value: 495.3883139815727
[[  0.           0.           0.         316.31065119   0.
    0.        ]]
316.31065118525817
max index: 3
max_value: 316.31065118525817
[[  0.         394.23539248 253.04852095   0.           0.
  496.31065119]]
496.31065118525817
max index: 5
max_value: 496.31065118525817
[[  0.         394.23539248 253.04852095   0.           0.
  496.31065119]]
496.31065118525817
max index: 5
max_value: 496.31065118525817
[[  0.           0.           0.         316.31065119   0.
    0.        ]]
316.31065118525817
max index: 3
max_value: 316.31065118525817
[[  0.           0.           0.         316.31065119   0.
  492.7942406 ]]
492.79424059620726
max index: 5
max_value: 492.79424059620726
[[  0.         394.23539248   0.           0.         395.38831398
  495.38831398]]
495.3883139815727
max index: 5
max_value: 495.3883139815727
[[  0.           0.           0.         316.31065119   0.
    0.        ]]
316.310651185

  498.48884273]]
498.48884272548185
max index: 5
max_value: 498.48884272548185
[[  0.         398.79107418   0.           0.         398.79107418
  498.48884273]]
498.48884272548185
max index: 5
max_value: 498.48884272548185
[[  0.         398.79107418 255.22628748   0.           0.
  498.48884273]]
498.48884272548185
max index: 5
max_value: 498.48884272548185
[[  0.           0.           0.         319.03285934   0.
    0.        ]]
319.03285934430846
max index: 3
max_value: 319.03285934430846
[[  0.         398.79107418 255.22628748   0.         398.79107418
    0.        ]]
398.7910741803855
max index > 1: 4
max_value: 398.7910741803855
[[  0.           0.           0.         319.03285934   0.
    0.        ]]
319.03285934430846
max index: 3
max_value: 319.03285934430846
[[  0.         398.79107418   0.           0.         398.79107418
  498.48884273]]
498.48884272548185
max index: 5
max_value: 498.48884272548185
[[  0.         398.79107418 255.22628748   0.           0.
  498.48

499.68308734994304
max index: 5
max_value: 499.68308734994304
[[  0.           0.           0.         319.50482398   0.
    0.        ]]
319.50482398428596
max index: 3
max_value: 319.50482398428596
[[  0.         399.60385919   0.           0.         399.74646988
  499.60385919]]
499.6038591874288
max index: 5
max_value: 499.6038591874288
[[  0.         399.60385919   0.           0.         399.74646988
  499.60385919]]
499.6038591874288
max index: 5
max_value: 499.6038591874288
[[  0.         399.68308735 255.60385919   0.         399.68308735
    0.        ]]
399.68308734994304
max index > 1: 1
max_value: 399.68308734994304
[[  0.           0.           0.         319.74646988   0.
  499.68308735]]
499.68308734994304
max index: 5
max_value: 499.68308734994304
[[  0.         399.74646988 255.60385919   0.           0.
  499.68308735]]
499.68308734994304
max index: 5
max_value: 499.68308734994304
[[  0.           0.           0.         319.50482398   0.
    0.        ]]
319.504823

  499.87019258]]
499.8701925785367
max index: 5
max_value: 499.8701925785367
[[  0.         399.89615406 255.9335386    0.           0.
  499.89615406]]
499.8961540628294
max index: 5
max_value: 499.8961540628294
[[  0.         399.89615406   0.           0.         399.91692325
  499.87019258]]
499.8701925785367
max index: 5
max_value: 499.8701925785367
[[  0.         399.89615406 255.9335386    0.           0.
  499.89615406]]
499.8961540628294
max index: 5
max_value: 499.8961540628294
[[  0.         399.89615406 255.9335386    0.           0.
  499.89615406]]
499.8961540628294
max index: 5
max_value: 499.8961540628294
[[  0.         399.89615406 255.9335386    0.         399.91692325
    0.        ]]
399.91692325026355
max index: 4
max_value: 399.91692325026355
[[  0.           0.           0.         319.9335386    0.
  499.89615406]]
499.8961540628294
max index: 5
max_value: 499.8961540628294
[[  0.         399.89615406 255.9335386    0.         399.91692325
    0.        ]]
399.9

    0.        ]]
399.9825775428137
max index: 1
max_value: 399.9825775428137
[[  0.         399.98257754 255.98884963   0.           0.
  499.97822193]]
499.97822192851714
max index: 5
max_value: 499.97822192851714
[[  0.         399.98257754   0.           0.         399.98257754
  499.97822193]]
499.97822192851714
max index: 5
max_value: 499.97822192851714
[[  0.         399.98257754 255.98884963   0.           0.
  499.98257754]]
499.9825775428137
max index: 5
max_value: 499.9825775428137
[[  0.         399.98257754 255.98884963   0.           0.
  499.98257754]]
499.9825775428137
max index: 5
max_value: 499.9825775428137
[[  0.           0.           0.         319.98606203   0.
  499.97822193]]
499.97822192851714
max index: 5
max_value: 499.97822192851714
[[  0.         399.98257754 255.98884963   0.         399.98606203
    0.        ]]
399.986062034251
max index: 4
max_value: 399.986062034251
[[  0.         399.98257754   0.           0.         399.98257754
  499.97822193]]
499

  499.9976616 ]]
499.9976615973804
max index: 5
max_value: 499.9976615973804
[[  0.           0.           0.         319.99850342   0.
    0.        ]]
319.9985034223235
max index: 3
max_value: 319.9985034223235
[[  0.         399.99634625 255.99880274   0.           0.
  499.99812928]]
499.99812927790435
max index: 5
max_value: 499.99812927790435
[[  0.           0.           0.         319.99850342   0.
  499.99812928]]
499.99812927790435
max index: 5
max_value: 499.99812927790435
[[  0.           0.           0.         319.99850342   0.
    0.        ]]
319.9985034223235
max index: 3
max_value: 319.9985034223235
[[  0.         399.99850342   0.           0.         399.99850342
  499.9976616 ]]
499.9976615973804
max index: 5
max_value: 499.9976615973804
[[  0.         399.99634625 255.99880274   0.           0.
  499.99812928]]
499.99812927790435
max index: 5
max_value: 499.99812927790435
[[  0.         399.99812928 255.99880274   0.         399.99634625
    0.        ]]
399.99812

  499.999387  ]]
499.99938700178376
max index: 5
max_value: 499.99938700178376
[[  0.         399.9995096  255.99968614   0.           0.
  499.999387  ]]
499.99938700178376
max index: 5
max_value: 499.99938700178376
[[  0.        399.9995096   0.          0.        399.9995096 499.999387 ]]
499.99938700178376
max index: 5
max_value: 499.99938700178376
[[  0.        399.9995096   0.          0.        399.9995096 499.999387 ]]
499.99938700178376
max index: 5
max_value: 499.99938700178376
[[  0.         399.9995096  255.99968614   0.         399.9995096
    0.        ]]
399.999509601427
max index > 1: 1
max_value: 399.999509601427
[[  0.           0.           0.         319.99960768   0.
  499.9995096 ]]
499.999509601427
max index: 5
max_value: 499.999509601427
[[  0.         399.99960768 255.99968614   0.         399.9995096
    0.        ]]
399.99960768114164
max index: 1
max_value: 399.99960768114164
[[  0.         399.9995096  255.99968614   0.           0.
  499.9995096 ]]
499.999

[[  0.         399.9999663  255.99995788   0.         399.99994734
    0.        ]]
399.9999663000668
max index: 1
max_value: 399.9999663000668
[[  0.         399.99993418 255.9999663    0.           0.
  499.99993418]]
499.99993417981784
max index: 5
max_value: 499.99993417981784
[[  0.           0.           0.         319.99997304   0.
    0.        ]]
319.9999730400534
max index: 3
max_value: 319.9999730400534
[[  0.         399.99993418 255.9999663    0.           0.
  499.99993418]]
499.99993417981784
max index: 5
max_value: 499.99993417981784
[[  0.         399.9999663  255.99997843   0.         399.99994734
    0.        ]]
399.9999663000668
max index: 1
max_value: 399.9999663000668
[[  0.         399.99993418 255.9999663    0.           0.
  499.99993418]]
499.99993417981784
max index: 5
max_value: 499.99993417981784
[[  0.         399.9999663    0.           0.         399.99994734
  499.99994734]]
499.9999473438543
max index: 5
max_value: 499.9999473438543
[[  0.         399

  499.99999117]]
499.9999911657648
max index: 5
max_value: 499.9999911657648
[[  0.           0.           0.         319.99999548   0.
  499.99999293]]
499.99999293261186
max index: 5
max_value: 499.99999293261186
[[  0.           0.           0.         319.99999548   0.
    0.        ]]
319.9999954768716
max index: 3
max_value: 319.9999954768716
[[  0.         399.99999117 255.99999638   0.           0.
  499.99999117]]
499.9999911657648
max index: 5
max_value: 499.9999911657648
[[  0.         399.99999435   0.           0.         399.99999293
  499.99999293]]
499.99999293261186
max index: 5
max_value: 499.99999293261186
[[  0.         399.99999117 255.99999638   0.           0.
  499.99999117]]
499.9999911657648
max index: 5
max_value: 499.9999911657648
[[  0.         399.99999435 255.99999548   0.         399.99998896
    0.        ]]
399.9999943460895
max index: 1
max_value: 399.9999943460895
[[  0.           0.           0.         319.99999548   0.
  499.99999435]]
499.9999943

[[  0.         399.99999905 255.99999924   0.           0.
  499.99999881]]
499.99999881428914
max index: 5
max_value: 499.99999881428914
[[  0.           0.           0.         319.99999905   0.
    0.        ]]
319.99999905143136
max index: 3
max_value: 319.99999905143136
[[  0.         399.99999881 255.99999924   0.         399.99999905
    0.        ]]
399.99999905143136
max index: 4
max_value: 399.99999905143136
[[  0.           0.           0.         319.99999924   0.
    0.        ]]
319.99999924114513
max index: 3
max_value: 319.99999924114513
[[  0.           0.           0.         319.99999924   0.
    0.        ]]
319.99999924114513
max index: 3
max_value: 319.99999924114513
[[  0.         399.99999905 255.99999939   0.           0.
  499.99999881]]
499.99999881428914
max index: 5
max_value: 499.99999881428914
[[  0.         399.99999881   0.           0.         399.99999905
  499.99999905]]
499.99999905143136
max index: 5
max_value: 499.99999905143136
[[  0.           0

  499.99999984]]
499.9999998408567
max index: 5
max_value: 499.9999998408567
[[  0.           0.           0.         319.99999992   0.
  499.99999984]]
499.9999998408567
max index: 5
max_value: 499.9999998408567
[[  0.         399.99999987 255.99999993   0.           0.
  499.99999987]]
499.99999987268535
max index: 5
max_value: 499.99999987268535
[[  0.         399.9999998  255.99999993   0.         399.9999999
    0.        ]]
399.9999998981483
max index: 4
max_value: 399.9999998981483
[[  0.         399.99999987   0.           0.         399.99999987
  499.99999984]]
499.9999998408567
max index: 5
max_value: 499.9999998408567
[[  0.         399.99999987   0.           0.         399.99999987
  499.99999987]]
499.99999987268535
max index: 5
max_value: 499.99999987268535
[[  0.         399.99999987   0.           0.         399.99999987
  499.9999999 ]]
499.9999998981483
max index: 5
max_value: 499.9999998981483
[[  0.           0.           0.         319.99999992   0.
  499.9999999

    0.        ]]
319.9999999829122
max index: 3
max_value: 319.9999999829122
[[  0.         399.99999997 255.99999998   0.           0.
  499.99999997]]
499.99999997330025
max index: 5
max_value: 499.99999997330025
[[  0.         399.99999997 255.99999998   0.           0.
  499.99999997]]
499.99999997330025
max index: 5
max_value: 499.99999997330025
[[  0.         399.99999997   0.           0.         399.99999998
  499.99999998]]
499.99999997864023
max index: 5
max_value: 499.99999997864023
[[  0.           0.           0.         319.99999998   0.
  499.99999997]]
499.9999999666253
max index: 5
max_value: 499.9999999666253
[[  0.           0.           0.         319.99999998   0.
  499.99999997]]
499.9999999666253
max index: 5
max_value: 499.9999999666253
[[  0.         399.99999997 255.99999998   0.           0.
  499.99999998]]
499.9999999829122
max index: 5
max_value: 499.9999999829122
[[  0.           0.           0.         319.99999998   0.
  499.99999997]]
499.9999999666253

[[  0. 400.   0.   0. 400. 500.]]
499.9999999985323
max index: 5
max_value: 499.9999999985323
[[  0. 400. 256.   0. 400.   0.]]
399.99999999882584
max index > 1: 1
max_value: 399.99999999882584
[[  0.   0.   0. 320.   0. 500.]]
499.99999999882584
max index: 5
max_value: 499.99999999882584
[[  0.   0.   0. 320.   0. 500.]]
499.99999999882584
max index: 5
max_value: 499.99999999882584
[[  0.   0.   0. 320.   0. 500.]]
499.99999999882584
max index: 5
max_value: 499.99999999882584
[[  0. 400. 256.   0.   0. 500.]]
499.9999999985323
max index: 5
max_value: 499.9999999985323
[[  0. 400. 256.   0.   0. 500.]]
499.9999999985323
max index: 5
max_value: 499.9999999985323
[[  0.   0.   0. 320.   0. 500.]]
499.99999999882584
max index: 5
max_value: 499.99999999882584
[[  0. 400. 256.   0. 400.   0.]]
399.9999999990607
max index: 1
max_value: 399.9999999990607
[[  0. 400.   0.   0. 400. 500.]]
499.9999999985323
max index: 5
max_value: 499.9999999985323
[[  0. 400. 256.   0.   0. 500.]]
499.99999999

max index: 5
max_value: 499.99999999969225
[[  0. 400. 256.   0.   0. 500.]]
499.9999999995191
max index: 5
max_value: 499.9999999995191
[[  0. 400. 256.   0. 400.   0.]]
399.9999999997538
max index: 1
max_value: 399.9999999997538
[[  0. 400. 256.   0. 400.   0.]]
399.9999999997538
max index: 1
max_value: 399.9999999997538
[[  0.   0.   0. 320.   0.   0.]]
319.99999999969225
max index: 3
max_value: 319.99999999969225
[[  0. 400. 256.   0.   0. 500.]]
499.9999999995191
max index: 5
max_value: 499.9999999995191
[[  0.   0.   0. 320.   0.   0.]]
319.99999999969225
max index: 3
max_value: 319.99999999969225
[[  0. 400.   0.   0. 400. 500.]]
499.9999999996153
max index: 5
max_value: 499.9999999996153
[[  0. 400.   0.   0. 400. 500.]]
499.9999999996153
max index: 5
max_value: 499.9999999996153
[[  0.   0.   0. 320.   0.   0.]]
319.99999999969225
max index: 3
max_value: 319.99999999969225
[[  0. 400.   0.   0. 400. 500.]]
499.9999999996153
max index: 5
max_value: 499.9999999996153
[[  0.   0.

max_value: 499.99999999997897
[[  0.   0.   0. 320.   0.   0.]]
319.9999999999866
max index: 3
max_value: 319.9999999999866
[[  0. 400. 256.   0. 400.   0.]]
399.9999999999832
max index > 1: 4
max_value: 399.9999999999832
[[  0. 400. 256.   0.   0. 500.]]
499.99999999997897
max index: 5
max_value: 499.99999999997897
[[  0. 400. 256.   0. 400.   0.]]
399.9999999999832
max index > 1: 4
max_value: 399.9999999999832
[[  0. 400. 256.   0.   0. 500.]]
499.99999999997897
max index: 5
max_value: 499.99999999997897
[[  0. 400. 256.   0.   0. 500.]]
499.99999999997897
max index: 5
max_value: 499.99999999997897
[[  0. 400.   0.   0. 400. 500.]]
499.99999999997897
max index: 5
max_value: 499.99999999997897
[[  0. 400. 256.   0.   0. 500.]]
499.9999999999832
max index: 5
max_value: 499.9999999999832
[[  0. 400. 256.   0.   0. 500.]]
499.9999999999832
max index: 5
max_value: 499.9999999999832
[[  0. 400.   0.   0. 400. 500.]]
499.99999999997897
max index: 5
max_value: 499.99999999997897
[[  0.   0. 

max index: 1
max_value: 399.9999999999983
[[  0. 400. 256.   0. 400.   0.]]
399.9999999999983
max index: 1
max_value: 399.9999999999983
[[  0. 400. 256.   0.   0. 500.]]
499.9999999999966
max index: 5
max_value: 499.9999999999966
[[  0.   0.   0. 320.   0. 500.]]
499.99999999999784
max index: 5
max_value: 499.99999999999784
[[  0.   0.   0. 320.   0. 500.]]
499.99999999999784
max index: 5
max_value: 499.99999999999784
[[  0. 400. 256.   0.   0. 500.]]
499.9999999999966
max index: 5
max_value: 499.9999999999966
[[  0. 400.   0.   0. 400. 500.]]
499.9999999999983
max index: 5
max_value: 499.9999999999983
[[  0. 400.   0.   0. 400. 500.]]
499.99999999999864
max index: 5
max_value: 499.99999999999864
[[  0. 400.   0.   0. 400. 500.]]
499.99999999999864
max index: 5
max_value: 499.99999999999864
[[  0. 400. 256.   0. 400.   0.]]
399.9999999999983
max index: 1
max_value: 399.9999999999983
[[  0.   0.   0. 320.   0.   0.]]
319.99999999999864
max index: 3
max_value: 319.99999999999864
[[  0. 4

max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
499.99999999999994
max index: 5
max_value: 499.99999999999994
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index: 1
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
499.99999999999994
max index: 5
max_value: 499.99999999999994
[[  0. 400. 256.   0.   0. 500.]]
499.99999999999994
max index: 5
max_value: 499.99999999999994
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index: 1
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index: 1
max_value: 4

max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_valu

max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0


max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max inde

500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
ma

400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
ma

max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max inde

[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0


max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0

[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0


500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]


[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  

max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0


[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  

500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max in

max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0


500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.

320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
ma

500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
ma

[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  

[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0. 

[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 4

[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 4

[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 40

max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max inde

[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 

[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0. 

[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0


500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max in

max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max

[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 4
max_value: 400.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0. 400. 256.   0. 400.   0.]]
400.0
max index > 1: 1
max_value: 400.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  

500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0.   0.]]
320.0
max index: 3
max_value: 320.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0.   0.   0. 320.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400. 256.   0.   0. 500.]]
500.0
max index: 5
max_value: 500.0
[[  0. 400.   0.   0. 400. 500.]]
500.0
max index: 5
m

In [28]:
# Normalize the "trained" Q matrix
print("Trained Q matrix:")
print(Q/np.max(Q)*100)

Trained Q matrix:
[[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


In [29]:
current_state = 2
steps = [current_state]
while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index, size=1))
    else:
        next_step_index = int(next_step_index)
    steps.append(next_step_index)
    current_state = next_step_index
# Print selected sequence of steps
print("Selected path:")
print(steps)

Selected path:
[2, 3, 1, 5]
